// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationCaisseEnregistreuse.Data;

#nullable disable

namespace WebApplicationCaisseEnregistreuse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplicationCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Informatique"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Littérature"
                        });
                });

            modelBuilder.Entity("WebApplicationCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Informatique",
                            Description = "Ordinateur portable haute performance",
                            ImageUrl = "url_de_l_image1.jpg",
                            Nom = "Ordinateur portable",
                            Prix = 999.99m,
                            QuantiteStock = 50
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Électronique",
                            Description = "Smartphone dernier cri",
                            ImageUrl = "url_de_l_image2.jpg",
                            Nom = "Smartphone",
                            Prix = 599.99m,
                            QuantiteStock = 30
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Littérature",
                            Description = "Livre captivant",
                            ImageUrl = "url_de_l_image3.jpg",
                            Nom = "Livre",
                            Prix = 19.99m,
                            QuantiteStock = 100
                        });
                });

            modelBuilder.Entity("WebApplicationCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.HasOne("WebApplicationCaisseEnregistreuse.Models.Categorie", null)
                        .WithMany("ListeProduits")
                        .HasForeignKey("CategorieId");
                });

            modelBuilder.Entity("WebApplicationCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Navigation("ListeProduits");
                });
#pragma warning restore 612, 618
        }
    }
}
